---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pihole
  namespace: pihole
spec:
  chart: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes
  targetNamespace: pihole
  valuesContent: |-
    DNS1: 1.1.1.1
    DNS2: 1.1.1.1
    extraEnvVars:
      WEBPASSWORD: foo
    dnsmasq:
      customDnsEntries:
        - address=/boyne.lab./192.168.6.10
        - address=/latham.lab./192.168.6.11

        - address=/prometheus.lab./192.168.6.221
        - address=/grafana.lab./192.168.6.221
        - address=/pihole.lab./192.168.6.222

    persistentVolumeClaim:
      enabled: true

    serviceTCP:
      loadBalancerIP: 192.168.6.222
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceUDP:
      loadBalancerIP: 192.168.6.222
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
