---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: monitoring
  valuesContent: |-
    alertmanager:
      enabled: false

    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
